class AuthError(Exception):
	pass

class ProtocolError(Exception):
	pass